FROM foo.install

COPY ccmts-vpp.tar.gz .
RUN tar -zxvf ccmts-vpp.tar.gz && \
    cd cmts-dp-vpp/src/plugins/ && \
    autoreconf -fis && \
    ./configure && \
    make && \
    make install

COPY *.init /




